[workspace]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "tcp"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
test-tcp = "mojo run test_tcp.mojo"
format = "mblack tcp.mojo test_tcp.mojo"

[dependencies]
mojo = ">=0.26.2"
